//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ bộ phận chăm sóc để giải quyết.
        /// </summary>
        public static string ErroException {
            get {
                return ResourceManager.GetString("ErroException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Mã khách hàng đã tồn tại&quot;.
        /// </summary>
        public static string ErroService_DuplicateCustomerCode {
            get {
                return ResourceManager.GetString("ErroService_DuplicateCustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Tên nhóm đã tồn tại&quot;.
        /// </summary>
        public static string ErroService_DuplicateCustomerGroupName {
            get {
                return ResourceManager.GetString("ErroService_DuplicateCustomerGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Mã nhân viên đã tồn tại&quot;.
        /// </summary>
        public static string ErroService_DuplicateEmployeeCode {
            get {
                return ResourceManager.GetString("ErroService_DuplicateEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Email đã tồn tại&quot;.
        /// </summary>
        public static string ErroService_DuplicateEmployeeEmail {
            get {
                return ResourceManager.GetString("ErroService_DuplicateEmployeeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Số chứng minh nhân dân đã tồn tại&quot;.
        /// </summary>
        public static string ErroService_DuplicateEmployeeIdentifyNumber {
            get {
                return ResourceManager.GetString("ErroService_DuplicateEmployeeIdentifyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Số điện thoại đã tồn tại&quot;.
        /// </summary>
        public static string ErroService_DuplicateEmployeePhone {
            get {
                return ResourceManager.GetString("ErroService_DuplicateEmployeePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Số điện thoại đã tồn tại&quot;.
        /// </summary>
        public static string ErroService_DuplicatePhoneNumber {
            get {
                return ResourceManager.GetString("ErroService_DuplicatePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã cửa hàng đã tồn tại.
        /// </summary>
        public static string ErroService_DuplicateShopCode {
            get {
                return ResourceManager.GetString("ErroService_DuplicateShopCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Mã nhân viên không được phép để trống&quot;.
        /// </summary>
        public static string ErroService_EmptyEmployeeCode {
            get {
                return ResourceManager.GetString("ErroService_EmptyEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Email không được phép để trống&quot;.
        /// </summary>
        public static string ErroService_EmptyEmployeeEmail {
            get {
                return ResourceManager.GetString("ErroService_EmptyEmployeeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Số chứng minh nhân dân không được phép để trống&quot;.
        /// </summary>
        public static string ErroService_EmptyEmployeeIdentifyNumber {
            get {
                return ResourceManager.GetString("ErroService_EmptyEmployeeIdentifyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Họ và tên không được phép để trống&quot;.
        /// </summary>
        public static string ErroService_EmptyEmployeeName {
            get {
                return ResourceManager.GetString("ErroService_EmptyEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Số điện thoại không được phép để trống&quot;.
        /// </summary>
        public static string ErroService_EmptyEmployeePhone {
            get {
                return ResourceManager.GetString("ErroService_EmptyEmployeePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Mã nhân viên không hợp lệ&quot;.
        /// </summary>
        public static string ErroService_ValidEmployeeCode {
            get {
                return ResourceManager.GetString("ErroService_ValidEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Email không hợp lệ&quot;.
        /// </summary>
        public static string ErroService_ValidEmployeeEmail {
            get {
                return ResourceManager.GetString("ErroService_ValidEmployeeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Nhân bản không thành công&quot;.
        /// </summary>
        public static string SuccessService_CloneNotSuccess {
            get {
                return ResourceManager.GetString("SuccessService_CloneNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Nhân bản thành công&quot;.
        /// </summary>
        public static string SuccessService_CloneSuccess {
            get {
                return ResourceManager.GetString("SuccessService_CloneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa không thành công.
        /// </summary>
        public static string SuccessService_DeleteNotSuccess {
            get {
                return ResourceManager.GetString("SuccessService_DeleteNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string SuccessService_DeleteSuccess {
            get {
                return ResourceManager.GetString("SuccessService_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm không thành công.
        /// </summary>
        public static string SuccessService_InsertNotSuccess {
            get {
                return ResourceManager.GetString("SuccessService_InsertNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thành công.
        /// </summary>
        public static string SuccessService_InsertSuccess {
            get {
                return ResourceManager.GetString("SuccessService_InsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Dữ liệu hợp lệ&quot;.
        /// </summary>
        public static string SuccessService_IsVaid {
            get {
                return ResourceManager.GetString("SuccessService_IsVaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi không thành công.
        /// </summary>
        public static string SuccessService_UpdateNotSuccess {
            get {
                return ResourceManager.GetString("SuccessService_UpdateNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi thành công.
        /// </summary>
        public static string SuccessService_UpdateSuccess {
            get {
                return ResourceManager.GetString("SuccessService_UpdateSuccess", resourceCulture);
            }
        }
    }
}
